import mongoose from 'mongoose';

export const TASK_CATEGORIES = [
  'PLUMBER',
  'ELECTRICIAN',
  'CARPENTER',
  'PAINTER',
  'TAILOR',
  'SHIFTING',
  'COOK',
  'MASON',
  'HVAC',
  'VEHICLE_MECHANIC',
  'VEHICLE_ELECTRICIAN',
  'HOUSE_HELP',
  'CAR_WASHER',
  'DRIVERS',
  'BABYSITTERS',
  'DOCTORS',
  'REAL_ESTATE_AGENTS',
];

const PLUMBER_SUBCATEGORIES = [
  'WATER_LINE_REPAIR',
  'DRAIN_CLEANING',
  'WATER_TANK_INSTALLATION',
  'FAUCET_INSTALLATION',
  'OTHERS',
];
const ELECTRICIAN_SUBCATEGORIES = [
  'WIRING',
  'UPS_INSTALLATION',
  'SOLAR_PANEL_INSTALLATION',
  'BREAKER_BOX_INSTALLATION',
  'OTHERS',
];
const CARPENTER_SUBCATEGORIES = [
  'FURNITURE_REPAIR',
  'FURNITURE_INSTALLATION',
  'DOOR_REPAIR',
  'DOOR_INSTALLATION',
  'OTHERS',
];
const PAINTER_SUBCATEGORIES = [
  'WALL_PAINTING',
  'FURNITURE_PAINTING',
  'WALLPAPER_INSTALLATION',
  'WALLPAPER_REMOVAL',
  'OTHERS',
];
const TAILOR_SUBCATEGORIES = [
  'CLOTHING_ALTERATION',
  'DRESSMAKING',
  'EMBROIDERY',
  'TAILORING',
  'OTHERS',
];
const SHIFTING_SUBCATEGORIES = [
  'RESIDENTIAL_SHIFTING',
  'COMMERCIAL_SHIFTING',
  'INTERCITY_SHIFTING',
  'PACKING',
  'UNPACKING',
  'OTHERS',
];
const COOK_SUBCATEGORIES = [
  'HOME_COOKING',
  'EVENT_CATERING',
  'PERSONAL_CHEF',
  'BAKING',
  'OTHERS',
];
const MASON_SUBCATEGORIES = [
  'BRICKLAYING',
  'PLASTERING',
  'TILING',
  'CONCRETE_WORK',
  'OTHERS',
];
const HVAC_SUBCATEGORIES = [
  'AC_INSTALLATION',
  'AC_REPAIR',
  'AC_CLEANING',
  'AC_GAS_REFILLING',
  'OTHERS',
];
const VEHICLE_MECHANIC_SUBCATEGORIES = [
  'CAR_REPAIR',
  'BIKE_REPAIR',
  'TRUCK_REPAIR',
  'BUS_REPAIR',
  'OTHERS',
];
const VEHICLE_ELECTRICIAN_SUBCATEGORIES = [
  'CAR_ELECTRICAL_REPAIR',
  'BIKE_ELECTRICAL_REPAIR',
  'TRUCK_ELECTRICAL_REPAIR',
  'BUS_ELECTRICAL_REPAIR',
  'OTHERS',
];
const HOUSE_HELP_SUBCATEGORIES = [
  'CLEANING',
  'COOKING',
  'BABYSITTING',
  'DRIVING',
  'OTHERS',
];
const CAR_WASHER_SUBCATEGORIES = [
  'CAR_WASHING',
  'BIKE_WASHING',
  'TRUCK_WASHING',
  'BUS_WASHING',
  'OTHERS',
];
const DRIVERS_SUBCATEGORIES = [
  'CAR_DRIVER',
  'BIKE_DRIVER',
  'TRUCK_DRIVER',
  'BUS_DRIVER',
  'OTHERS',
];
const BABYSITTERS_SUBCATEGORIES = [
  'BABYSITTING',
  'TUTORING',
  'PLAYING',
  'FEEDING',
  'OTHERS',
];
const DOCTORS_SUBCATEGORIES = [
  'GENERAL_PHYSICIAN',
  'DENTIST',
  'CARDIOLOGIST',
  'DERMATOLOGIST',
  'OTHERS',
];
const REAL_ESTATE_AGENTS_SUBCATEGORIES = [
  'BUYING',
  'SELLING',
  'RENTING',
  'LEASE',
  'OTHERS',
];

export const categorySubCategories = {
  PLUMBER: PLUMBER_SUBCATEGORIES,
  ELECTRICIAN: ELECTRICIAN_SUBCATEGORIES,
  CARPENTER: CARPENTER_SUBCATEGORIES,
  PAINTER: PAINTER_SUBCATEGORIES,
  TAILOR: TAILOR_SUBCATEGORIES,
  SHIFTING: SHIFTING_SUBCATEGORIES,
  COOK: COOK_SUBCATEGORIES,
  MASON: MASON_SUBCATEGORIES,
  HVAC: HVAC_SUBCATEGORIES,
  VEHICLE_MECHANIC: VEHICLE_MECHANIC_SUBCATEGORIES,
  VEHICLE_ELECTRICIAN: VEHICLE_ELECTRICIAN_SUBCATEGORIES,
  HOUSE_HELP: HOUSE_HELP_SUBCATEGORIES,
  CAR_WASHER: CAR_WASHER_SUBCATEGORIES,
  DRIVERS: DRIVERS_SUBCATEGORIES,
  BABYSITTERS: BABYSITTERS_SUBCATEGORIES,
  DOCTORS: DOCTORS_SUBCATEGORIES,
  REAL_ESTATE_AGENTS: REAL_ESTATE_AGENTS_SUBCATEGORIES,
};

const CategorySchema = new mongoose.Schema({
  name: { type: String, required: true, unique: true },
  subCategories: { type: [String] },
});

const Category = mongoose.model('Category', CategorySchema);
export default Category;
